name: CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: garygrossgarten/github-action-scp@v0.5.3
      with: 
        password: ${{ secrets.norm_ssh_password }}
        host: norm.im
        username: deploy
        local: ./
        remote: /opt/ukcmg/
