name: Auto tag on Wechat QRCode uploaded

on:
  push:
    paths:
      - 'src/wx.jpg'
    branches:
      - master
  workflow_dispatch:
    inputs:
      file:
        description: "file path to wx.jpg"
        required: true
        default: "src/wx.jpg"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: fregante/setup-git-user@v1
    - name: private registry
      run: npm set registry https://npm.norm.im --scope=@normanzb
    - name: deps
      run: npm i
    - name: tag it
      run: |
        git checkout master
        git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        npm version patch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: dispatch deploy
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: deploy
