name: Auto tag on Wechat QRCode uploaded

on:
  push:
    paths:
      - 'src/wx.jpg'
  workflow_dispatch:
    inputs:
      file:
        description: "file path to wx.jpg"
        required: true
        default: "src/wx.jpg"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: fregante/setup-git-user@v1
    - name: private registry
      run: npm set registry https://npm.norm.im --scope=@normanzb
    - name: deps
      run: npm i
    - name: tag it
      run: npm version patch
